#!/usr/bin/env python3

import sys
import argparse
import time

try:
    import kismetexternal
except:
    print("ERROR:  Kismet external Python tools require the kismetexternal python ")
    print("        library; you can find it in the kismetexternal git or via pip")
    sys.exit(1)


class KillEndpoint(object):
    def __init__(self):
        self.parser = argparse.ArgumentParser(
            description="Kismet External Python Example"
        )

        self.parser.add_argument("--in-fd", action="store", type=int, dest="infd")
        self.parser.add_argument("--out-fd", action="store", type=int, dest="outfd")

        self.results = self.parser.parse_args()

        if self.results.infd is None or self.results.outfd is None:
            print("ERROR:  Kismet external python tools are (typically) launched by ")
            print("        Kismet itself; running it on its own won't do what you want")
            sys.exit(1)

        self.kei = kismetexternal.ExternalInterface(
            self.results.infd, self.results.outfd
        )

        # self.kei.debug = True

        self.kei.start()

        self.kei.add_uri_handler("GET", "/proxytest/python.html", self.handle_uri)

    def handle_uri(self, externalhandler, request):
        print(
            "PYTHON - Handle web req {} {} {}".format(
                request.req_id, request.method, request.uri
            )
        )
        externalhandler.send_http_response(
            request.req_id, "<html><body><b>This is from python!</b></body></html>"
        )

    def loop(self):
        while self.kei.is_running():
            self.kei.send_ping()
            time.sleep(1)

        self.kei.kill()


if __name__ == "__main__":
    kill_endpoint = KillEndpoint()
    kill_endpoint.loop()
